version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - static_volume:/var/www/html/static
      - media_volume:/var/www/html/media

  web:
    build: ./django 
    command: gunicorn django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - ./django/.env

volumes:
  static_volume:
  media_volume:
