version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params  # uwsgi_params 파일 추가
      - /var/www/fintechproject/Server/Html:/var/www/html/custom
      - /etc/letsencrypt:/etc/letsencrypt  # Let's Encrypt SSL 설정 파일 공유
      - static_volume:/var/www/html/static
      - media_volume:/var/www/html/media
    networks:
      - mynetwork

  web:
    build:
      context: ./DjangoServer
      dockerfile: Dockerfile
    command: uwsgi --ini uwsgi.ini
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./logs:/app/logs
    expose:
      - "8000"  
    env_file:
      - ./DjangoServer/.env
    networks:
      - mynetwork

volumes:
  static_volume:
  media_volume:

networks:
  mynetwork:
