version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/www/fintechproject/Server/templates:/var/www/templates/custom
      - /etc/letsencrypt:/etc/letsencrypt
      - static_volume:/var/www/templates/static
      - media_volume:/var/www/templates/media
    networks:
      - mynetwork

  web:
    build:
      context: .
      dockerfile: ./DjangoServer/Dockerfile
    command: >
      gunicorn DjangoServer.wsgi:application
      --bind 0.0.0.0:8000
      --access-logfile /app/logs/gunicorn_access.log
      --error-logfile /app/logs/gunicorn_error.log
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - ./logs:/app/logs
    expose:
      - "8000"
    env_file:
      - ./DjangoServer/.env
    networks:
      - mynetwork

  redis:
    image: "redis:alpine"
    networks:
      - mynetwork

  celery:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    networks:
      - mynetwork

  celery-beat:
    build: .
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    networks:
      - mynetwork

volumes:
  static_volume:
  media_volume:

networks:
  mynetwork:
