version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/www/fintechproject/Server/Html:/var/www/html/custom
      - /etc/letsencrypt:/etc/letsencrypt
      - static_volume:/var/www/html/static
      - media_volume:/var/www/html/media
    networks:
      - mynetwork

  web:
    build:
      context: ./DjangoServer
      dockerfile: Dockerfile
    command: uwsgi --ini /app/DjangoServer/uwsgi.ini
    volumes:
      - ./DjangoServer:/app  # Django 애플리케이션 디렉토리 마운트
      - static_volume:/app/static
      - media_volume:/app/media
      - ./logs:/app/logs
    expose:
      - "8000"
    env_file:
      - ./DjangoServer/.env
    networks:
      - mynetwork

volumes:
  static_volume:
  media_volume:

networks:
  mynetwork:
